INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('Fish tricks', now() - '21 days'::INTERVAL, 'This is content'),
    ('Not Dogs', now() - '21 days'::INTERVAL, 'This is content'),
    ('Bluffalo Wings', now() - '21 days'::INTERVAL, 'This is content'),
    ('SubstiTuna Salad', now() - '21 days'::INTERVAL, 'This is content'),
    ('Tofurkey', now() - '21 days'::INTERVAL, 'This is content'),
    ('Pretenderloins', now() - '9 days'::INTERVAL, 'This is content'),
    ('Steak-believe', now() - '9 days'::INTERVAL, 'This is content'),
    ('Kale Seitan', now() - '9 days'::INTERVAL, 'This is content'),
    ('NoBull Burger', now() - '9 days'::INTERVAL, 'This is content'),
    ('Turnip the Beet', now() - '9 days'::INTERVAL, 'This is content'),
    ('Mascarphony', now() - '7 days'::INTERVAL, 'This is content'),
    ('Burgatory', now() - '7 days'::INTERVAL, 'This is content'),
    ('Sleight of Ham', now() - '5 days'::INTERVAL, 'This is content'),
    ('Antichovies', now() - '5 days'::INTERVAL, 'This is content'),
    ('Lettuce B. Frank', now() - '5 days'::INTERVAL, 'This is content'),
    ('Pepperphony', now() - '5 days'::INTERVAL, 'This is content'),
    ('Shamburger', now() - '4 days'::INTERVAL, 'This is content'),
    ('Facon', now() - '4 days'::INTERVAL, 'This is content'),
    ('Salami-get-this', now() - '4 days'::INTERVAL, 'This is content'),
    ('Mi-steak', now() - '3 days'::INTERVAL, 'This is content'),
    ('Ghost Beef', now() - '3 days'::INTERVAL, 'This is content'),
    ('Cheatloaf', now() - '3 days'::INTERVAL, 'This is content'),
    ('Fried Trickin', now() - '3 days'::INTERVAL, 'This is content'),
    ('Salmock', now() - '3 days'::INTERVAL, 'This is content'),
    ('Leaf Stroganoff', now() - '2 days'::INTERVAL, 'This is content'),
    ('Chicken Noodle', now() - '2 days'::INTERVAL, 'This is content'),
    ('Pep-parody Pizza', now() - '2 days'::INTERVAL, 'This is content'),
    ('Arti-fish-al pie', now() - '1 days'::INTERVAL, 'This is content'),
    ('Bolphony sandwich', now(), 'This is content'),
    ('Chili non-carne', now(), 'This is content'),
    ('Don''t go bacon', now(), 'This is content')
;